import type { Post } from '@/payload-types'

// Dutch blog posts about screen time for SchermBlij
export const blogPostsData: Partial<Post>[] = [
  {
    title: '5 Praktische Tips voor Schermvrije Gezinsmomenten',
    slug: '5-tips-schermvrije-gezinsmomenten',
    meta: {
      title: '5 Praktische Tips voor Schermvrije Gezinsmomenten | SchermBlij',
      description: 'Ontdek hoe je thuis succesvol schermvrije momenten creëert. Praktische tips voor meer verbinding en minder schermtijd in het gezin.',
    },
    publishedAt: new Date('2024-12-01').toISOString(),
    _status: 'published',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In onze digitale wereld is het creëren van schermvrije momenten essentieel voor gezinsbinding. Hier zijn vijf bewezen strategieën die iedere familie kan toepassen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '1. Maak van maaltijden een heilig moment',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Leg alle apparaten weg tijdens het eten. Dit geeft ruimte voor echte gesprekken en bewuste waardering van het eten. Kinderen leren zo de waarde van onderlinge aandacht.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'Waarom Verveling Goed is voor Kinderen',
    slug: 'verveling-goed-voor-kinderen',
    meta: {
      title: 'Waarom Verveling Goed is voor Kinderen | SchermBlij',
      description: 'Ontdek waarom verveling essentieel is voor de ontwikkeling van kinderen en hoe je weerstand kunt bieden aan de neiging om schermen als oplossing te gebruiken.',
    },
    publishedAt: new Date('2024-11-15').toISOString(),
    _status: 'published',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '"Mam, ik verveel me!" - een uitspraak die vele ouders doet grijpen naar de tablet. Maar verveling is juist een cadeau voor de ontwikkeling van je kind.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Creativiteit bloeit in stilte',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Verveling activeert het standaard-modus netwerk in de hersenen - hetzelfde netwerk dat verantwoordelijk is voor creativiteit en probleemoplossing. Wanneer kinderen zich vervelen, gaan ze automatisch op zoek naar alternatieven.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'Sociale Media en Tieners: Een Gids voor Ouders',
    slug: 'sociale-media-tieners-gids-ouders',
    meta: {
      title: 'Sociale Media en Tieners: Een Gids voor Ouders | SchermBlij',
      description: 'Praktische tips voor ouders om tieners veilig te begeleiden in het gebruik van sociale media. Van privacy tot cyberpesten - alles wat je moet weten.',
    },
    publishedAt: new Date('2024-10-28').toISOString(),
    _status: 'published',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Sociale media zijn niet meer weg te denken uit het leven van tieners. Als ouder kun je je kind het beste begeleiden door mee te gaan in hun digitale wereld in plaats van ertegen te vechten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Begrijp de platforms die je kind gebruikt',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Neem de tijd om te begrijpen wat TikTok, Instagram en Snapchat inhouden. Vraag je tiener om het uit te leggen - dit toont interesse en respect voor hun wereld.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
  {
    title: 'Schermtijd Richtlijnen per Leeftijd: Wat Zegt de Wetenschap?',
    slug: 'schermtijd-richtlijnen-leeftijd-wetenschap',
    meta: {
      title: 'Schermtijd Richtlijnen per Leeftijd: Wat Zegt de Wetenschap? | SchermBlij',
      description: 'Wetenschappelijk onderbouwde richtlijnen voor schermtijd per leeftijdsgroep. Van baby tot tiener - ontdek wat experts aanbevelen.',
    },
    publishedAt: new Date('2024-10-10').toISOString(),
    _status: 'published',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Hoeveel schermtijd is gezond voor mijn kind? Deze vraag houdt veel ouders bezig. De wetenschap geeft ons gelukkig steeds meer inzicht in wat verantwoord schermgebruik betekent per leeftijd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '0-2 jaar: Samen kijken is de sleutel',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voor baby\'s en peuters staat sociale interactie centraal. Als er gekeken wordt, doe dit dan samen en maak het interactief door te praten over wat je ziet.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
  },
]